---
- hosts: localhost
  tasks:
    - name: update apt list
      become: true
      apt: 
        update_cache: yes
        upgrade: 'yes'

    - name: Install various via apt
      apt: 
        name: 
          - r-base
          # Pdf utilities
          - ocrmypdf
          - ghostscript
        state: present
        
    - name: Install various via snap
      become: true
      community.general.snap:
        name:
          - zotero-snap
          - sublime-merge
          - sublime-text
          - pycharm-professional

    # - name: Download and install Zotero
    #   become: true
    #   unarchive:
    #     src: https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=5.0.95
    #     dest: /opt/zotero
    #     remote_src: yes

    - name: Download Zotero & Better Bibtex add-on
    # # https://retorque.re/zotero-better-bibtex/
      get_url:
        url: "{{ item }}"
        dest: "~/Downloads/"
      loop:
        - https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=5.0.95
        - https://github.com/retorquere/zotero-better-bibtex/releases/download/v5.2.117/zotero-better-bibtex-5.2.117.xpi