---
- hosts: localhost
  tasks:
    - name: update apt list
      become: true
      apt: 
        upgrade: yes
        update_cache: yes
    - name: Install R
      become: true
      apt: pkg=r-base state=latest
