---
- hosts: localhost
  tasks:
    - name: update apt list
      become: true
      apt: 
        update_cache: yes
        upgrade: 'yes'
    - name: Install R
      apt: 
        name: r-base
        state: present
